/****************************************************************************


popid.h

produced by Borland Resource Workshop


*****************************************************************************/

#define DIALOG_39	39
#define DIALOG_36	36
#define PSPRECORDDLG	1110
#define ICON_2	103
#define DIALOG_1	1
#define PSCONFIGDLG	1100
#define ID_PSWORDNUM	543
#define ID_LEFTBUTTON	106
#define ID_SUFFIX	346
#define	ID_UKSPELL	348
#define ID_PSCASESEARCH	104
#define ID_FIXWIDTH	11
#define ID_PSDELAY	101
#define IDC_RTEXT1	18
#define ID_DOAUTOLINKSRCH	13
#define PSMAINMENU	50
#define CMW_PRECORD	134
#define	CMW_MARKHISTORY	135
#define	CMW_MARKNWORDS	136
#define	CMW_RECEXPHISTORY	137
#define	CMW_TTS	140
#define CMW_RECORD	168
#define CMW_PLAYTTS	169
#define	CMW_SEARCH	302
#define	CMW_CLOSEMENU	303
#define CM_FILESAVE	24333
#define CM_FILTER	130
#define	CM_FILEHISTORY	4000
#define CM_EDITREPLACECB	22001
#define CM_FINDBACK	24332
#define CM_FINDNEXT	24328
#define CM_EDITENABLEAUTOSEARCH	22
#define CM_FILEALLCLOSE	24331
#define CM_EDITPOPUPSEARCH	21
#define CM_HELPCONTENTS	114
#define CM_EDITSELECTALL	24327
#define PSMENU_1	51
#define CM_SEARCHRUN	855
#define CM_PSCONFIG	1
#define CM_FILEEXIT	101


